name: Download Artifact and Commit
env:
  REPO_NAME: btwiusearch.net
on:
  push:
    branches:
      - main

jobs:
  download:
    name: Get
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - house-of-vanity/rexec
          - house-of-vanity/desubot
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: robinraju/release-downloader@v1.8
      id: download
      with:
        repository: ${{ matrix.repo }}
        latest: true
        fileName: "*.zst"
    - name: Get name
      run: echo "PKG_NAME=$(echo ${{ matrix.repo }} | awk -F '/' '{print $NF}')" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v3.1.2
      if: fromJson(steps.download.outputs.downloaded_files)[0]
      name: Upload artifact
      with:
        name: ${{ env.PKG_NAME }}
#       path: ${{ fromJson(steps.download.outputs.downloaded_files)[0] }}
        path: "*.zst"
        if-no-files-found: ignore
  update:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --user 1001
    needs:
      - download
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        name: Download
        id: download
        with:
          path: pkgs/
      - name: Update database
        run: |
          mv pkgs/*/*zst x86_64/
          cd x86_64/
          repo-add  ${{ env.REPO_NAME }}.db.tar.gz *.zst
          ls -lah ../
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          new_branch: repo

