name: Download Artifact and Commit
env:
  REPO_NAME: btwiusearch.net
on:
# repository_dispatch:
#   types: [new_artifact]
  push:
    branches:
      - main

jobs:
  download:
    name: Get
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --user 1001
    strategy:
      matrix:
        repo:
          - house-of-vanity/rexec
          - house-of-vanity/desubot
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: robinraju/release-downloader@v1.8
      id: download
      with:
        repository: ${{ matrix.repo }}
        latest: true
        fileName: "*.zst"
#   - name: Get pkg name
#     run: echo "VERSION=$(grep -P '^version = \"\d+\.\d+\.\d+\"' Cargo.toml | awk -F '\"' '{print $2}')" >> $GITHUB_ENV
    - name: Get name
      run: echo "PKG_NAME=$(echo ${{ matrix.repo }} | awk -F '/' '{print $NF}')" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v3.1.2
      if: fromJson(steps.download.outputs.downloaded_files)[0]
      name: Upload artifact
      with:
        name: ${{ env.PKG_NAME }}
        path: ${{ fromJson(steps.download.outputs.downloaded_files)[0] }}
        if-no-files-found: ignore
  update:
    runs-on: ubuntu-latest
    needs:
      - download
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          new_branch: repo

