name: Download Artifact and Commit
env:
  REPO_NAME: btwiusearch.net
on:
# repository_dispatch:
#   types: [new_artifact]
  push:
    branches:
      - main

jobs:
  download:
    name: Download ZST
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --user 1001
    strategy:
      matrix:
        repo:
          - house-of-vanity/rexec
          - house-of-vanity/desubot
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: robinraju/release-downloader@v1.8
      with:
        repository: ${{ matrix.repo }}
        latest: true
        fileName: "*.zst"
    - name: Perform actions
      run: |
        ls -lah
        cd x86_64
        repo-add ${{ env.REPO_NAME }}.db.tar.gz *.zst
#   - name: Commit and push
#     run: |
#       git config --local user.email "repo_master@github.com"
#       git config --local user.name "GitHub Action"
#       git add -A
#       git commit -m "Update from artifact"
#       git push

